### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by haesleinhuepf** [clij/clij-deployment#1]
Hey Gaby @turekg ,

thanks for your great work on this. It seems that this could make my life so much easier. However, at the moment, build is failing with error messages like:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project clij-coremem: Failed to deploy artifacts: Could not transfer artifact net.haesleinhuepf:clij-coremem:jar:2.0.0.10 from/to scijava.releases (https://maven.scijava.org/content/repositories/releases/): Transfer failed for https://maven.scijava.org/content/repositories/releases/net/haesleinhuepf/clij-coremem/2.0.0.10/clij-coremem-2.0.0.10.jar 400 Bad Request -> [Help 1]
```

Do you know what that means? Does one have to configure the counter side somehow?

Thanks!

Cheers,
Robert

**Comment by turekg** [comment]
Hum, because of all the changes due to the hacking of the imagej.net <http://imagej.net/> wiki it suspect that the authentication credentials need to be updated. I will double check with Curtis. In the meantime, I could upload the artifacts manually? Let me know. It may also be useful for you to have an account there to do the same in case something like this happens. I’ll also mention this to Curtis.
Gaby

**Comment by haesleinhuepf** [comment]
Hey Gaby,

thanks for the quick feedback. No worries for now. The old deployment system still works. We can switch to the new when everything works nicely and stable. Thanks for taking care!

Cheers,
Robert

**Comment by turekg** [comment]
Hi Robert, so apparently the server hosting maven had a problem yesterday with space. That’s been cleared out and you should retry again. OTOH the 400 code is usually a problem with the client, so if it happens again I will investigate. Also Curtis said I should give you and account on the server so you can manage your deployments (for example if you want to delete something)
I will set up one for you and send you the password, which you can then change to whatever you want.
Cheers
Gaby

**Comment by haesleinhuepf** [comment]
Hey Gaby @turekg 

are there any news on this? I just ran the deployment again and the error message contains:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project clij-coremem: Failed to deploy artifacts: Could not transfer artifact net.haesleinhuepf:clij-coremem:jar:2.0.0.10 from/to scijava.releases (https://maven.scijava.org/content/repositories/releases/): Transfer failed for https://maven.scijava.org/content/repositories/releases/net/haesleinhuepf/clij-coremem/2.0.0.10/clij-coremem-2.0.0.10.jar 400 Bad Request -> [Help 1]
```

I'm also CCing @maarzt because he might be curious as well.

Thanks for your support!

Cheers,
Robert

**Comment by maarzt** [comment]
Yes, I'm curious. It would help me a lot if this works!

**Comment by turekg** [comment]
It’s a server error I’ll have to look at the logs and see what exactly the problem is

**Comment by turekg** [comment]
I’ve created a proxy on scijava maven for the bintray repo, let me know how that works. It is by far the best solution.
gaby

**Comment by haesleinhuepf** [comment]
> It is by far the best solution.

I agree! 

@maarzt could you please test it? Current release is 2.1.4.7

Thanks to both of you! :-)

**Comment by maarzt** [comment]
@haesleinhuepf This now works perfectly! Thank you @turekg. It finds all the required artifacts on maven.scijava.org now.

**Comment by haesleinhuepf** [comment]
Fantastic. It now also shows up in maven.scijava.org

![image](https://user-images.githubusercontent.com/12660498/94794139-c7382a00-03db-11eb-9dcc-0f779786fbd2.png)

Thanks @turekg  and thanks for testing  @maarzt !

**Comment by maarzt** [comment]
@haesleinhuepf It's maybe interesting for you to know that the artifacts from your bintray repository will only show up at maven.scijava.org if somebody downloaded them. maven.scijava.org now behaves like a proxy to your bintray repository.
clij2 2.1.4.7 and 2.1.4.0 are visible because I just used them in my maven project ;)
